apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - image: redis:5.0.7
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: drkiq-redis
      restartPolicy: Always
      volumes:
        - name: drkiq-redis
          persistentVolumeClaim:
            claimName: drkiq-redis
